<include file="Common/header" />
<body>
    <div class="container theme-showcase">
        <form class="form-horizontal">
            <?php foreach ($list as $module) { ?>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" class="permissionIds" data-id="<?php echo $module['id']; ?>" value="1" <?php echo $module['permission'] == '1' ? "checked" : ""; ?>>
                        <?php echo $module['name']; ?>
                    </label>
                </div>
                <?php if (count($module['child'])) { ?>
                    <?php foreach ($module['child'] as $menu) { ?>
                        <div class="checkbox">
                            &nbsp;&nbsp;&nbsp;&nbsp;|_
                            <label>
                                <input type="checkbox" class="permissionIds" data-id="<?php echo $menu['id']; ?>" value="1" <?php echo $menu['permission'] == '1' ? "checked" : ""; ?>>
                                <?php echo $menu['name']; ?>
                            </label>
                        </div>
                        <?php if (count($menu['child'])) { ?>
                            <div class="checkbox">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_
                                <?php foreach ($menu['child'] as $action) { ?>
                                    <label class="checkbox-inline">
                                        <input type="checkbox" class="permissionIds" data-id="<?php echo $action['id']; ?>" value="1" <?php echo $action['permission'] == '1' ? "checked" : ""; ?>>
                                        <?php echo $action['name']; ?>
                                    </label>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
            <p></p><br />
            <div class="form-group">
                <div class="col-sm-offset-1 col-sm-9">
                    <input type="hidden" name='roleid' id="roleid" value='<?php echo $id; ?>'>
                    <button type="button" class="btn btn-primary" id="save"  data-loading-text="提交中...">提交</button>                          
                </div>
            </div>
        </form>
    </div>
    <script>
        $("#save").click(function () {
            var permissionIds = '';
            $("input.permissionIds:checked").each(function () {
                permissionIds += $(this).attr('data-id') + ',';
            });
            var roleId = $("#roleid").val();
            show_dialog({
                title: "操作确认",
                html: '确认选中权限授权用户组？',
                submit_callback: function () {
                    var url = "http://" + "<?php echo BASE_URL . "__CONTROLLER__" . "/rolePermission"; ?>";
                    $.ajax({
                        type: 'POST',
                        data: {roleId: roleId, permissionIds: permissionIds},
                        url: url,
                        cache: false,
                        dataType: "json",
                        success: function (data) {
                            show_dialog({
                                title: "返回信息",
                                html: data.msg,
                                cancel: false,
                                submit_callback: function () {
                                    window.location.reload();
                                    return false;
                                }
                            });
                        }
                    });
                }
            });
            return false;

        });
    </script>
<include file="Common/footer" />