<include file="Common/header" />
<body>
<include file="Common/menu" />
<div class="container theme-showcase">
    <header>
        <h1>游戏服务器配置列表<!--<a class="btn btn-primary" id="add" href="javascript:void(0)">添加</a>--></h1>
    </header>
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>服名</th>
                    <th>服标识</th>
                    <th>主机地址</th>
                    <th>数据库名</th>
                    <th>账号</th>
                    <th>密码</th>
                    <th>端口</th>
                    <th>类型</th>
                    <!--<th>操作</th>-->
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list as $v) { ?>                
                    <tr>
                        <td><?php echo $v['name']; ?></td>
                        <td><?php echo $v['nstring']; ?></td>
                        <td><?php echo $v['host']; ?></td>
                        <td><?php echo $v['dbname']; ?></td>
                        <td><?php echo $v['account']; ?></td>
                        <td><?php echo $v['pwd']; ?></td>
                        <td><?php echo $v['port']; ?></td>
                        <td><?php echo $v['stype'] == '1' ? "游戏服" : "command"; ?></td>
                        <!--
                        <td>
                            <i class="glyphicon glyphicon-edit"></i><a href="javascript:void(0)" class='pedit'  data-id='<?php echo $v['id'] ?>' data-toggle="tooltip" title="编辑">编辑</a>
                            <i class="glyphicon glyphicon-trash"></i><a class="cartoon-delete" href="javascript:void(0);" data-id="<?php echo $v['id'] ?>" data-toggle="tooltip" title="删除">删除</a>
                        </td>
                        -->
                    </tr>
                <?php } ?>
            </tbody>            
        </table>
    </div>
    <nav><?php echo $page; ?></nav>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel" data-id='0' data-act='0'>添加</h4>
            </div>
            <div class="alert alert-danger hidden" role="alert" id='warn'>
                <strong>错误!</strong>
            </div>
            <div class="alert alert-success hidden" role="alert" id='success'>
                <strong>成功!</strong>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="inputAccount" class="col-sm-3 control-label">Account</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputAccount" name="account" placeholder="account">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAccount" class="col-sm-3 control-label">name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputName" name="name" placeholder="name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputPassword" name="password" placeholder="Password">
                        </div>
                    </div>                    
                    <div class="form-group">
                        <label class="col-sm-3 control-label">是否锁定账号</label>
                        <div class="col-sm-9">
                            <label><input type="radio" name="status" id="inputStatus" value="1"  />是</label>
                            <label><input type="radio" name="status" id="inputStatus" value="0" checked/>否</label>            
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">是否超级账号</label>
                        <div class="col-sm-9">
                            <label><input type="radio" name="isadmin" id="inputIsadmin" value="1" />是</label>
                            <label><input type="radio" name="isadmin" id="inputIsadmin" value="0" checked/>否</label>            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input type="hidden" name='url' id='url' value='add'>
                            <button type="button" class="btn btn-primary" id="save"  data-loading-text="提交中...">提交</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal" id='closemodel'>关闭</button>                            
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
//        show_dialog({
//            title: "详细信息",
//            html: "<h1>111</h1>",
//            submit_callback: function () {
//                alert(this);
//            }
//        });
        $("#add").click(function (event) {
            event.preventDefault();
            $('#myModal').modal({show: true});

        });
        $("#closemodel").click(function (event) {
            window.location.reload();

        });
        $(".pedit").click(function () {     //获取编辑内容
            event.preventDefault();
            var ele = $(this);
            var id = ele.attr('data-id');
            var url = "http://" + "<?php echo BASE_URL . "__CONTROLLER__" . "/edit"; ?>";
            $.ajax({
                type: 'POST',
                data: {id: id,act:1},
                url: url,
                cache: false,
                dataType: "json",
                success: function (data) {
                    if (data.code == 1) {
                        $("#myModalLabel").attr("data-id", data.data.id);
                        $("#myModalLabel").attr("data-act", 2);

                        $("#myModalLabel").html("编辑账号" + data.data.account);
                        $("#inputAccount").val(data.data.account);
                        $("#inputPassword").val(data.data.password);
                        $("#inputName").val(data.data.name);
                        $("#url").val("edit");
                        $("#inputStatus[value=" + data.data.status + "]").attr("checked", 'checked');
                        $("#inputIsadmin[value=" + data.data.isadmin + "]").attr("checked", 'checked');

                        $('#myModal').modal({show: true});
                    }
                    else {
                        alert(data.msg);
                        return false;
                    }
                }
            });
        });
        $(".cartoon-delete").click(function () {
            var ele = $(this);
            show_dialog({
                title: "删除确认",
                html: "一旦删除不可恢复，确认删除？",
                submit_callback: function () {
                    $(".modal-backdrop").remove();
                    var id = ele.attr('data-id');
                    var url = "http://" + "<?php echo BASE_URL . "__CONTROLLER__" . "/del"; ?>";
                    $.ajax({
                        type: 'POST',
                        data: {id: id},
                        url: url,
                        cache: false,
                        dataType: "json",
                        success: function (data) {
                            show_dialog({
                                title: "返回信息",
                                html: data.msg,
                                cancel: false,
                                submit_callback: function () {
                                    window.location.reload();
                                    return false;
                                }
                            });
                        }
                    });
                }
            });
            return false;
        });
        $("#save").click(function (event) {
            event.preventDefault();
            var btn = $(this).button('loading')
            var account = $("#inputAccount").val();
            var password = $("#inputPassword").val();
            var iname = $("#inputName").val();
            var istatus = $("#inputStatus:checked").val();
            var isadmin = $('#inputIsadmin:checked').val();
            var id = $("#myModalLabel").attr("data-id");
            var act = $("#myModalLabel").attr("data-act");
            var url = $("#url").val();
            if (account == '') {
                $("#warn").html("<strong>错误!</strong> 账号不能为空");
                $("#warn").removeClass("hidden");
                btn.button('reset');
                return false;
            }
            if (password == '') {
                $("#warn").html("<strong>错误!</strong> 密码不能为空");
                $("#warn").removeClass("hidden");
                btn.button('reset');
                return false;
            }
            // business logic...
            //btn.button('reset')
            var url = "http://" + "<?php echo BASE_URL . "__CONTROLLER__/"; ?>" + url;
            $.ajax({
                type: 'POST',
                data: {account: account, password: password, iname: iname, istatus: istatus, isadmin: isadmin,id:id,act:act},
                url: url,
                cache: false,
                dataType: "json",
                success: function (data) {
                    if (data) {
                        if (data.code == 1) {
                            $("#success").html("<strong>成功!</strong> " + data.msg);
                            $("#success").removeClass("hidden");
                            window.location.reload();
                        }
                        else {
                            $("#warn").html("<strong>错误!</strong> " + data.msg);
                            $("#warn").removeClass("hidden");
                            btn.button('reset')
                        }
                    }
                }
            });

        });
    });
</script>
<include file="Common/footer" />
