<include file="Common/header" />
<body>
<include file="Common/menu" />
<div class="container">
    <div class="alert alert-danger hidden " role="alert" id='warn'>
        <strong>错误!</strong> Change a few things up and try submitting again.
    </div>
    <div class="alert alert-success hidden" role="alert" id='success'>
        <strong>成功!</strong> You successfully read this important alert message.
    </div>
    <form class="form-signin">
        <h2 class="form-signin-heading" id='t1'>修改密码</h2>
        <label for="inputOldpwd" class="sr-only">旧密码</label>
        <input type="password" id="inputOldpwd" class="form-control" placeholder="旧密码" required autofocus>
        <label class="list-inline"></label>
        <label for="inputNewpwd" class="sr-only">新密码</label>
        <input type="password" id="inputNewpwd" class="form-control" placeholder="新密码" required>
        <label for="inputRepwd" class="sr-only">新密码</label>
        <input type="password" id="inputRepwd" class="form-control" placeholder="再次输入" required>
        <!--
        <div class="checkbox">
          <label>
            <input type="checkbox"  value="remember-me"> Remember me
          </label>
        </div>
        -->
        <button class="btn btn-lg btn-primary btn-block" type="submit" id='sub' autocomplete="off" data-loading-text="Loading...">提交</button>
    </form>
</div> <!-- /container -->  
<script>
    $('#sub').on('click', function (event) {
        event.preventDefault();
        var btn = $(this).button('loading')
        var oldpwd = $("#inputOldpwd").val();
        var newpwd = $("#inputNewpwd").val();
        var repwd = $("#inputRepwd").val();
        // business logic...
        if (oldpwd == '') {
            $("#warn").html("<strong>错误!</strong> 旧密码必须填写");
            $("#warn").removeClass("hidden");
            btn.button('reset');
            return;
        }
        if(newpwd == ''){
            $("#warn").html("<strong>错误!</strong> 新密码必须填写");
            $("#warn").removeClass("hidden");
            btn.button('reset');
            return;
        }
        if(newpwd != repwd){
            $("#warn").html("<strong>错误!</strong> 2次密码填写不正确");
            $("#warn").removeClass("hidden");
            btn.button('reset');
            return;
        }
        if(newpwd == oldpwd){
            $("#warn").html("<strong>错误!</strong> 新旧密码不能一样");
            $("#warn").removeClass("hidden");
            btn.button('reset');
            return;
        }
        var url = "http://" + "<?php echo BASE_URL . "__CONTROLLER__" . "/setpwd"; ?>";
        $.ajax({
            type: 'POST',
            data: {oldpwd: oldpwd, newpwd: newpwd,repwd:repwd},
            url: url,
            cache: false,
            dataType: "json",
            success: function (data) {
                if (data) {
                    if (data.code == 1) {
                        $("#success").html("<strong>成功!</strong> " + data.msg);
                        $("#success").removeClass("hidden");
                        $("#warn").addClass("hidden");
                        btn.button('reset')
                    }
                    else {
                        $("#warn").html("<strong>错误!</strong> " + data.msg);
                        $("#warn").removeClass("hidden");
                        $("#success").addClass("hidden");
                        btn.button('reset')
                    }
                }
            }
        });
    });
</script>
<include file="Common/footer" />
